services:
  app:
    build: .
    image: laravel-app:latest
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: postgres-db
    environment:
      POSTGRES_DB: bundesland_finder
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
